# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-09-06 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='categoria',
            new_name='category',
        ),
    ]
