from .index import index
from .about import about
from .show_category import show_category
from .add_category import Add_Category
from .add_page import Add_Page
from .register import register
from .user_login import user_login
from .user_logout import user_logout
from .track_url import track_url
from .like_category import like_category
from .restricted import restricted
